### ISSUE TITLE
Model consumes GPU-0 even if I specify other gpus

### ISSUE THREAD

**Issue by neverUseThisName** [hukkelas/DSFD-Pytorch-Inference#24]
I have 4 gpus, I try to use gpu 1,2,3 other than 0:
`face_detection.build_detector('RetinaNetMobileNetV1', device=torch.device('cuda:1') )`
But it still consumes some memory on gpu-0. I guess some part of the model still runs on gpu-0.

**Comment by agirbau** [comment]
I have the same issue. I think the bug is in line 22 of https://github.com/hukkelas/DSFD-Pytorch-Inference/blob/7bbe1f61ef5cb951a6e55e0a80e4972419edf5ca/face_detection/dsfd/detect.py#L14-L27

where the model is set in the default device (cuda:0) with torch_utils.get_device(). I'll check and do a pull request.

**Comment by hukkelas** [comment]
Thanks! The PR is now merged to master
